### ISSUE TITLE
Brainstorm Roadmap 

### ISSUE THREAD

**Issue by joelthe1** [BibleNLP/assistant.bible#80]
- API
   - Stable auth token
- Support agents
   - need more details
   - Central controlling agent that coordinates actions
- Include images (and other modalities?)!
   - Find datasets
- Multi-language support
  - via MT
  - Target fixed number of languages
  - Add a layer at the user-interaction point
- Setup with more public content
   - CCEL
   - UW data
- STT and TTS
- Reproducible data loading
   - Data partitioning strategies

**Comment by ryderwishart** [comment]
Some updates:

- Data
	- clean up data? 
	- add more data? 
- Platform functionality
	- stable auth token 
	- capture usage
	- add evaluation and feedback
	- tests
- agentive qa? 
	- simple functions to return information
	- clarify
- review logs to harvest user queries
- project
- add a second LLM (PredictionGuard?)
- Ryder integration with some kind of plugin (vague at this point)

**Comment by ryderwishart** [comment]
Next priorities (in order):

- [ ] stable auth token #118, refs #53
- [ ] better source document transparency (e.g., show document snippet or title along with filename)
- [ ] add evaluation and feedback (thumbs up or down) ([types of human feedback](https://www.latent.space/p/humanloop)) #25 
    - allow testers to add comments about a thumbs up or down
    - track 'I don't know' answers
    - come up with a plan for how to leverage this
    - frameworks for capturing feedback? Host an open source one?
